import http from "node:http";import fs from "node:fs";import crypto from "node:crypto";
const PORT=process.env.PORT||10000,P=Object.freeze({version:5,seed:550033,train:120,test:100,transfer:100,steps:22,primaryWindow:[11,16],pass:"paired gain CI95 low > 0; frozen representation unchanged"});
const N=["bias","width","height","area","mean","cx","cy","aspectSigned","aspectAbs","fill","cx*mean","cy*mean","width*mean","height*mean"];
let S={phase:"train",episode:0,step:0,tickCount:0,lastTickAt:null,complete:false,w:Array(N.length).fill(0),trainSamples:0,test:{n:0,m:0,b:0,g:[]},transfer:{n:0,m:0,b:0,g:[]},frozenAt:null,frozenHash:null,integrity:{pixelOnlyTraining:true,noSemanticFeature:true,noPhaseRemap:true,predictionBeforeOutcome:true,frozenUnchanged:true}};
let H=[],F=null,pending=null;
function rng(n){let x=(P.seed+n*2654435761)>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}function phase(e){return e<120?"train":e<220?"test":e<320?"transfer":"complete"}
function W(e,t){const z=rng(e+9000)>.5?1:-1,tr=e>=220,x0=18+rng(e+3000)*25,y0=55+rng(e+4000)*45,vx=4.8+rng(e+5000)*2,vy=-.35+rng(e+6000)*.7,fx=tr?90+rng(e+7000)*100:110+rng(e+7000)*45;let x=x0+vx*t,y=y0+vy*t;if(t>10){let q=t-10;x+=.34*z*q*q;y+=.13*z*q*q}return{x,y,z,fx}}
function render(g,e,t){const w=80,h=45,p=new Uint8Array(w*h);p.fill(Math.floor(rng(e*100+t+8000)*7));const tr=e>=220,cx=Math.max(9,Math.min(71,Math.round(g.fx/4))),cy=tr?6+Math.floor(rng(e+8100)*31):11+Math.floor(rng(e+8100)*18),L=tr?8:5,Q=tr?2:1,I=tr?120+Math.floor(rng(e+8200)*28):155+Math.floor(rng(e+8200)*30),hw=g.z>0?L:Q,hh=g.z>0?Q:L;for(let yy=-hh;yy<=hh;yy++)for(let xx=-hw;xx<=hw;xx++){let X=cx+xx,Y=cy+yy;if(X>=0&&X<w&&Y>=0&&Y<h)p[Y*w+X]=I}let ox=Math.max(1,Math.min(78,Math.round(g.x/4))),oy=Math.max(1,Math.min(43,Math.round(g.y/4)));for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++)p[(oy+yy)*w+ox+xx]=245;return{p,w,h}}
function observe(im,t){let sx=0,sy=0,no=0,minx=99,maxx=-1,miny=99,maxy=-1,sum=0,n=0;for(let y=0;y<im.h;y++)for(let x=0;x<im.w;x++){let v=im.p[y*im.w+x];if(v>220){sx+=x;sy+=y;no++}else if(v>100){minx=Math.min(minx,x);maxx=Math.max(maxx,x);miny=Math.min(miny,y);maxy=Math.max(maxy,y);sum+=v;n++}}return{obj:no?{x:sx/no,y:sy/no,step:t}:null,field:n>6?{w:maxx-minx+1,h:maxy-miny+1,area:n,mean:sum/n,cx:(minx+maxx)/2,cy:(miny+maxy)/2}:null}}
function features(f){if(!f)return null;let w=f.w/20,h=f.h/20,a=f.area/250,m=f.mean/255,x=f.cx/80,y=f.cy/45,s=(f.w-f.h)/(f.w+f.h),ab=Math.abs(s),fill=f.area/(f.w*f.h);return[1,w,h,a,m,x,y,s,ab,fill,x*m,y*m,w*m,h*m]}
function dot(a,b){return a.reduce((s,x,i)=>s+x*b[i],0)}function pred(){let h=H.filter(Boolean).slice(-2);if(h.length<2)return null;let[a,b]=h,vx=(b.x-a.x)/(b.step-a.step),vy=(b.y-a.y)/(b.step-a.step),base={x:b.x+vx,y:b.y+vy},q=F?dot(S.w,F):0;return{base,model:{x:base.x+q,y:base.y+q*.38}}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function ci(xs){if(!xs.length)return null;let m=xs.reduce((a,b)=>a+b,0)/xs.length,v=xs.length>1?xs.reduce((s,x)=>s+(x-m)**2,0)/(xs.length-1):0,d=1.96*Math.sqrt(v/xs.length);return{mean:m,low:m-d,high:m+d}}function score(q){let z=ci(q.g);return{tests:q.n,modelError:q.n?q.m/q.n:null,baselineError:q.n?q.b/q.n:null,gain:q.n?(q.b-q.m)/q.n:null,gainCI95:z,supported:!!z&&z.low>0}}
function hash(){return crypto.createHash("sha256").update(JSON.stringify(S.w)).digest("hex")}function ranked(){return N.map((name,i)=>({name,weight:S.w[i],magnitude:Math.abs(S.w[i])})).sort((a,b)=>b.magnitude-a.magnitude)}
function report(){return{phase:S.phase,episode:S.episode,totalEpisodes:320,step:S.step,tickCount:S.tickCount,lastTickAt:S.lastTickAt,trainSamples:S.trainSamples,representation:ranked(),test:score(S.test),transfer:score(S.transfer),frozenAt:S.frozenAt,frozenHash:S.frozenHash,integrity:S.integrity,complete:S.complete}}
function tick(){if(S.complete)return;S.tickCount++;S.lastTickAt=new Date().toISOString();S.phase=phase(S.episode);if(S.tickCount%220===0)console.log("V5_HEARTBEAT",JSON.stringify({phase:S.phase,episode:S.episode,step:S.step,tickCount:S.tickCount}));let g=W(S.episode,S.step),o=observe(render(g,S.episode,S.step),S.step);if(o.field)F=features(o.field);
if(pending&&S.phase!=="train"&&o.obj&&S.step>=11&&S.step<=16){let actual=o.obj,me=dist(pending.model,actual),be=dist(pending.base,actual),q=S.phase==="test"?S.test:S.transfer;q.n++;q.m+=me;q.b+=be;q.g.push(be-me)}
if(S.phase==="train"&&o.obj&&H.filter(Boolean).length>=2&&S.step>=11&&S.step<=16&&F){let h=H.filter(Boolean).slice(-2),[a,b]=h,vx=(b.x-a.x)/(b.step-a.step),target=o.obj.x-(b.x+vx),err=target-dot(S.w,F),lr=.018,l1=.00008;for(let i=0;i<S.w.length;i++){S.w[i]+=lr*err*F[i];if(i)S.w[i]-=l1*Math.sign(S.w[i])}S.trainSamples++}
H.push(o.obj);pending=pred();S.step++;if(S.step>=22){S.episode++;S.step=0;H=[];F=null;pending=null;if(S.episode===120){S.frozenAt=new Date().toISOString();S.frozenHash=hash();console.log("V5_TRAIN_COMPLETE",JSON.stringify(report()))}if(S.episode===220)console.log("V5_TEST_COMPLETE",JSON.stringify(report()));if(S.episode>120&&hash()!==S.frozenHash){S.integrity.frozenUnchanged=false;throw Error("frozen representation mutated")}if(S.episode>=320){S.phase="complete";S.complete=true;console.log("V5_COMPLETE",JSON.stringify(report()));return}}setTimeout(tick,35)}
const dash=fs.readFileSync(new URL("./code33-dashboard.html",import.meta.url),"utf8");http.createServer((req,res)=>{if(req.url==="/api"){res.setHeader("content-type","application/json");return res.end(JSON.stringify({service:"CODE33 Development Lab",protocol:P,report:report()}))}res.setHeader("content-type","text/html; charset=utf-8");res.end(dash)}).listen(PORT,()=>console.log("CODE33 Lab v5 listening",PORT));tick();