import http from "node:http";
import fs from "node:fs";
const PORT=process.env.PORT||10000;
const protocol=Object.freeze({version:3,seed:330033,trainEpisodes:60,testEpisodes:60,transferEpisodes:60,steps:24,baseline:"constant-velocity",frozenAfterTrain:true,passRule:"95% CI of paired gain must be above 0"});
let state={phase:"train",episode:0,step:0,trainSamples:0,memorySize:0,test:{n:0,modelSum:0,baseSum:0,gains:[]},transfer:{n:0,modelSum:0,baseSum:0,gains:[]},frozenAt:null,complete:false};
let history=[],pending=null,memory=[];
function rng(n){let x=(protocol.seed+n*2654435761)>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}
function phase(ep){return ep<60?"train":ep<120?"test":ep<180?"transfer":"complete"}
function world(ep,step){const kind=Math.floor(rng(ep+2000)*4),tr=ep>=120,x0=20+rng(ep+3000)*35,y0=45+rng(ep+4000)*65,vx=4+rng(ep+5000)*4,vy=-1+rng(ep+6000)*2;let x=x0+vx*step,y=y0+vy*step;if(kind===3&&step>10){const t=step-10;x+=(tr?.7:.35)*t*t;y+=(tr?.35:.18)*t*t}const exists=!(kind===2&&step>=12);const visible=exists&&!(x>=138&&x<=182);return{x,y,exists,visible,kind}}
function render(gt,ep,step){const W=80,H=45,p=new Uint8Array(W*H),noise=Math.floor(rng(ep*100+step+7000)*8);p.fill(noise);if(gt.visible){const cx=Math.max(1,Math.min(W-2,Math.round(gt.x/4))),cy=Math.max(1,Math.min(H-2,Math.round(gt.y/4)));for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++)p[(cy+yy)*W+cx+xx]=245}return{p,W,H}}
function observe(img,step){let sx=0,sy=0,n=0;for(let y=0;y<img.H;y++)for(let x=0;x<img.W;x++)if(img.p[y*img.W+x]>200){sx+=x;sy+=y;n++}return n?{x:sx/n,y:sy/n,step}:null}
function sig(h){if(h.length<3)return null;const a=h[h.length-3],b=h[h.length-2],c=h[h.length-1];return[(b.x-a.x)/(b.step-a.step),(b.y-a.y)/(b.step-a.step),(c.x-b.x)/(c.step-b.step),(c.y-b.y)/(c.step-b.step)]}
function correction(s){if(!s||!memory.length)return{x:0,y:0};const near=memory.map(m=>({m,d:Math.sqrt(s.reduce((z,v,i)=>z+(v-m.s[i])**2,0))})).sort((a,b)=>a.d-b.d).slice(0,9);let x=0,y=0,w=0;for(const q of near){const z=1/(.05+q.d);x+=q.m.o.x*z;y+=q.m.o.y*z;w+=z}return{x:x/w,y:y/w}}
function predict(){const h=history.filter(Boolean).slice(-3);if(h.length<2)return null;const a=h[h.length-2],b=h[h.length-1],dt=b.step-a.step,vx=(b.x-a.x)/dt,vy=(b.y-a.y)/dt,base={x:b.x+vx,y:b.y+vy},c=correction(sig(h));return{base,model:{x:base.x+c.x,y:base.y+c.y}}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function ci95(xs){if(!xs.length)return null;const mean=xs.reduce((a,b)=>a+b,0)/xs.length;if(xs.length<2)return{mean,low:mean,high:mean};const variance=xs.reduce((a,b)=>a+(b-mean)**2,0)/(xs.length-1),m=1.96*Math.sqrt(variance/xs.length);return{mean,low:mean-m,high:mean+m}}
function score(b){const ci=ci95(b.gains);return{tests:b.n,modelError:b.n?b.modelSum/b.n:null,baselineError:b.n?b.baseSum/b.n:null,gain:b.n?(b.baseSum-b.modelSum)/b.n:null,gainCI95:ci,supported:!!ci&&ci.low>0}}
function report(){return{phase:state.phase,episode:state.episode,step:state.step,trainSamples:state.trainSamples,memorySize:state.memorySize,test:score(state.test),transfer:score(state.transfer),position:score({n:state.test.n+state.transfer.n,modelSum:state.test.modelSum+state.transfer.modelSum,baseSum:state.test.baseSum+state.transfer.baseSum,gains:[...state.test.gains,...state.transfer.gains]}),existence:{tests:0,accuracy:null,baselineAccuracy:null},frozenAt:state.frozenAt,complete:state.complete}}
function tick(){if(state.complete)return;state.phase=phase(state.episode);const gt=world(state.episode,state.step),obs=observe(render(gt,state.episode,state.step),state.step);
if(pending&&state.phase!=="train"&&obs){const actual={x:gt.x/4,y:gt.y/4},me=dist(pending.model,actual),be=dist(pending.base,actual),b=state.phase==="test"?state.test:state.transfer;b.n++;b.modelSum+=me;b.baseSum+=be;b.gains.push(be-me)}
if(state.phase==="train"&&obs){const h=history.filter(Boolean).slice(-2);if(h.length===2){const a=h[0],b=h[1],d1=b.step-a.step,d2=obs.step-b.step;if(d1===1&&d2===1){const s=sig([...h,obs]);const o={x:obs.x-2*b.x+a.x,y:obs.y-2*b.y+a.y};if(s){memory.push({s,o});state.trainSamples++;state.memorySize=memory.length}}}}
history.push(obs);pending=predict();state.step++;if(state.step>=protocol.steps){state.episode++;state.step=0;history=[];pending=null;if(state.episode===protocol.trainEpisodes){state.frozenAt=new Date().toISOString();console.log("LAB_PHASE train_complete",JSON.stringify(report()))}if(state.episode===protocol.trainEpisodes+protocol.testEpisodes)console.log("LAB_PHASE test_complete",JSON.stringify(report()));if(state.episode>=180){state.phase="complete";state.complete=true;console.log("LAB_COMPLETE",JSON.stringify(report()));return}}setTimeout(tick,50)}
const dashboard=fs.readFileSync(new URL("./code33-dashboard.html",import.meta.url),"utf8");
http.createServer((req,res)=>{if(req.url==="/api"){res.setHeader("content-type","application/json");return res.end(JSON.stringify({service:"CODE33 Development Lab",protocol,report:report()}))}res.setHeader("content-type","text/html; charset=utf-8");res.end(dashboard)}).listen(PORT,()=>console.log("CODE33 Lab v3 listening",PORT));
tick();
